triforce-blitz.python.include-system-path=true
triforce-blitz.python.names[0]=python3
triforce-blitz.python.names[1]=python
triforce-blitz.python.names[2]=python3.exe
triforce-blitz.python.names[3]=python.exe
triforce-blitz.generator.blacklisted-branches[0]=sgl2022
triforce-blitz.generator.blacklisted-branches[1]=sgl2023
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
